CREATE TABLE TB_WALLETS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    OWNER_ID RAW(16) NOT NULL,
    OWNER_TYPE VARCHAR2(20) NOT NULL,
    BALANCE NUMBER(15, 2) DEFAULT 0 NOT NULL,
    PENDING_BALANCE NUMBER(15, 2) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_WALLETS_OWNER UNIQUE (OWNER_ID, OWNER_TYPE)
);

CREATE TABLE TB_WALLET_TRANSACTIONS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    WALLET_ID RAW(16) NOT NULL,
    TYPE VARCHAR2(40) NOT NULL,
    AMOUNT NUMBER(15, 2) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    REFERENCE_ID VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_WALLET_TRANSACTIONS_WALLET
        FOREIGN KEY (WALLET_ID)
        REFERENCES TB_WALLETS (ID)
);

CREATE TABLE TB_PAYMENT_TRANSACTIONS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ORDER_ID RAW(16) NOT NULL,
    LOCAL_ORDER_ID VARCHAR2(100),
    CUSTOMER_ID RAW(16),
    SELLER_ID RAW(16),
    STORE_ID RAW(16) NOT NULL,
    AMOUNT NUMBER(15, 2) NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    FAILURE_REASON VARCHAR2(255),
    GATEWAY_REFERENCE VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PROCESSED_AT TIMESTAMP,
    CONSTRAINT UK_PAYMENT_TRANSACTIONS_ORDER UNIQUE (ORDER_ID)
);