CREATE TABLE KNOWLEDGE_CHUNK (
    ID bigint IDENTITY(1,1) PRIMARY KEY,
    SOURCE_NAME varchar(120) NOT NULL,
    TITLE varchar(200) NOT NULL,
    CHUNK_INDEX int NOT NULL,
    CONTENT varchar(max) NOT NULL,
    NORMALIZED_CONTENT varchar(max) NOT NULL
);

CREATE INDEX IDX_KNOWLEDGE_CHUNK_SOURCE
ON KNOWLEDGE_CHUNK (SOURCE_NAME);

CREATE INDEX IDX_KNOWLEDGE_CHUNK_SOURCE_CHUNK
ON KNOWLEDGE_CHUNK (SOURCE_NAME, CHUNK_INDEX);
