CREATE TABLE TB_USERS (
    ID uniqueidentifier PRIMARY KEY,
    NAME varchar(120) NOT NULL,
    EMAIL varchar(120) NOT NULL UNIQUE,
    PASSWORD varchar(255) NOT NULL,
    ROLE varchar(20) NOT NULL,
    CPF varchar(14) NOT NULL,
    PHONE varchar(20) NOT NULL,
    CREATED_AT datetime2 NOT NULL,
    CONSTRAINT UK_USERS_CPF UNIQUE (CPF)
);

CREATE TABLE TB_STORES (
    ID uniqueidentifier PRIMARY KEY,
    NAME varchar(120) NOT NULL,
    CATEGORY varchar(80) NOT NULL,
    USER_ID uniqueidentifier NOT NULL,
    CREATED_AT datetime2 NOT NULL,
    CONSTRAINT FK_STORE_USER
        FOREIGN KEY (USER_ID)
        REFERENCES TB_USERS(ID)
);

CREATE TABLE TB_CUSTOMER_OFFLINE_SESSIONS (
    ID uniqueidentifier PRIMARY KEY,
    USER_ID uniqueidentifier NOT NULL,
    SESSION_TOKEN varchar(255) NOT NULL,
    EXPIRES_AT datetime2 NOT NULL,
    ACTIVE bit NOT NULL,
    CREATED_AT datetime2 NOT NULL,
    CONSTRAINT FK_CUSTOMER_OFFLINE_USER
        FOREIGN KEY (USER_ID)
        REFERENCES TB_USERS(ID),
    CONSTRAINT UK_CUSTOMER_OFFLINE_USER
        UNIQUE (USER_ID),
    CONSTRAINT UK_CUSTOMER_OFFLINE_TOKEN
        UNIQUE (SESSION_TOKEN)
);
