CREATE TABLE TB_PAYMENT_PROCESSED_OUTBOX (
    ID RAW(16) PRIMARY KEY,
    ORDER_ID RAW(16) NOT NULL,
    EVENT_TYPE VARCHAR2(60) NOT NULL,
    PAYLOAD_JSON CLOB NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    ATTEMPTS NUMBER(10) DEFAULT 0 NOT NULL,
    NEXT_ATTEMPT_AT TIMESTAMP NOT NULL,
    LAST_ERROR VARCHAR2(255),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    SENT_AT TIMESTAMP,

    CONSTRAINT FK_PAYMENT_PROCESSED_OUTBOX_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES TB_PAYMENT_TRANSACTIONS(ORDER_ID)
);

CREATE UNIQUE INDEX UK_PAYMENT_PROCESSED_OUTBOX_ORDER
ON TB_PAYMENT_PROCESSED_OUTBOX (ORDER_ID);

CREATE INDEX IDX_PAYMENT_PROCESSED_OUTBOX_STATUS_NEXT
ON TB_PAYMENT_PROCESSED_OUTBOX (STATUS, NEXT_ATTEMPT_AT);
