ALTER TABLE TB_CATALOG_SYNC_LOGS ADD OPERATION_ID VARCHAR2(100);

CREATE UNIQUE INDEX UK_CATALOG_SYNC_OPERATION_ID
ON TB_CATALOG_SYNC_LOGS (
    CASE WHEN OPERATION_ID IS NOT NULL THEN OPERATION_ID END
);
