BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "tb_catalog_sync_logs" ADD "operation_id" VARCHAR2(100)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 AND SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "TB_CATALOG_SYNC_LOGS" ADD "OPERATION_ID" VARCHAR2(100)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 AND SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE UNIQUE INDEX "uk_catalog_sync_operation_id"
        ON "tb_catalog_sync_logs" (
            CASE WHEN "operation_id" IS NOT NULL THEN "operation_id" END
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 AND SQLCODE != -942 AND SQLCODE != -904 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE UNIQUE INDEX "UK_CATALOG_SYNC_OPERATION_ID"
        ON "TB_CATALOG_SYNC_LOGS" (
            CASE WHEN "OPERATION_ID" IS NOT NULL THEN "OPERATION_ID" END
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 AND SQLCODE != -942 AND SQLCODE != -904 THEN
            RAISE;
        END IF;
END;
/
