BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "tb_catalog_sync_logs" DROP COLUMN "device_id"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-904, -942) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "TB_CATALOG_SYNC_LOGS" DROP COLUMN "DEVICE_ID"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-904, -942) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "tb_orders" DROP COLUMN "device_id"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-904, -942) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "TB_ORDERS" DROP COLUMN "DEVICE_ID"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-904, -942) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "tb_order_sync_logs" DROP COLUMN "device_id"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-904, -942) THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "TB_ORDER_SYNC_LOGS" DROP COLUMN "DEVICE_ID"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-904, -942) THEN
            RAISE;
        END IF;
END;
/
