CREATE TABLE TB_PRODUCT_CATEGORIES (
    ID RAW(16) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    ACTIVE NUMBER(1) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE TB_PRODUCTS (
    ID RAW(16) PRIMARY KEY,
    STORE_ID RAW(16) NOT NULL,
    CATEGORY_ID RAW(16) NOT NULL,
    NAME VARCHAR2(120) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    PRICE NUMBER(10, 2) NOT NULL,
    STOCK_QUANTITY NUMBER(10) NOT NULL,
    ACTIVE NUMBER(1) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,

    CONSTRAINT FK_PRODUCTS_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES TB_PRODUCT_CATEGORIES(ID)
);