CREATE TABLE TB_CATALOG_SYNC_LOGS (
    ID RAW(16) PRIMARY KEY,
    STORE_ID RAW(16) NOT NULL,
    PRODUCT_ID RAW(16),
    DEVICE_ID VARCHAR2(150),
    OPERATION VARCHAR2(50) NOT NULL,
    QUANTITY_DELTA NUMBER(10),
    PRODUCT_NAME VARCHAR2(120),
    CATEGORY_ID RAW(16),
    PRICE NUMBER(10, 2),
    STOCK_QUANTITY NUMBER(10),
    LOCAL_UPDATED_AT TIMESTAMP NOT NULL,
    SYNCED_AT TIMESTAMP NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    MESSAGE VARCHAR2(255),

    CONSTRAINT FK_CATALOG_SYNC_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES TB_PRODUCTS(ID)
);