CREATE TABLE TB_ORDERS (
    ID RAW(16) PRIMARY KEY,
    LOCAL_ORDER_ID VARCHAR2(100),
    STORE_ID RAW(16) NOT NULL,
    CUSTOMER_ID RAW(16),
    SELLER_ID RAW(16),
    DEVICE_ID VARCHAR2(150),
    ORDER_STATUS VARCHAR2(40) NOT NULL,
    PAYMENT_STATUS VARCHAR2(40) NOT NULL,
    SYNC_STATUS VARCHAR2(40) NOT NULL,
    TOTAL_AMOUNT NUMBER(10, 2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    OFFLINE_CREATED_AT TIMESTAMP
);

CREATE TABLE TB_ORDER_ITEMS (
    ID RAW(16) PRIMARY KEY,
    ORDER_ID RAW(16) NOT NULL,
    PRODUCT_ID RAW(16) NOT NULL,
    PRODUCT_NAME VARCHAR2(120) NOT NULL,
    UNIT_PRICE NUMBER(10, 2) NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    TOTAL_PRICE NUMBER(10, 2) NOT NULL,

    CONSTRAINT FK_ORDER_ITEMS_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES TB_ORDERS(ID),

    CONSTRAINT FK_ORDER_ITEMS_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES TB_PRODUCTS(ID)
);

CREATE UNIQUE INDEX UK_ORDERS_DEVICE_LOCAL
ON TB_ORDERS (DEVICE_ID, LOCAL_ORDER_ID);