DROP INDEX UK_ORDERS_DEVICE_LOCAL;

CREATE UNIQUE INDEX UK_ORDERS_DEVICE_LOCAL
ON TB_ORDERS (
    CASE WHEN LOCAL_ORDER_ID IS NOT NULL THEN DEVICE_ID END,
    CASE WHEN LOCAL_ORDER_ID IS NOT NULL THEN LOCAL_ORDER_ID END
);