BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX "uk_orders_device_local"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 AND SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX "UK_ORDERS_DEVICE_LOCAL"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 AND SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE UNIQUE INDEX "uk_orders_device_local"
        ON "tb_orders" (
            CASE WHEN "local_order_id" IS NOT NULL THEN "device_id" END,
            CASE WHEN "local_order_id" IS NOT NULL THEN "local_order_id" END
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 AND SQLCODE != -942 AND SQLCODE != -904 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE UNIQUE INDEX "UK_ORDERS_DEVICE_LOCAL"
        ON "TB_ORDERS" (
            CASE WHEN "LOCAL_ORDER_ID" IS NOT NULL THEN "DEVICE_ID" END,
            CASE WHEN "LOCAL_ORDER_ID" IS NOT NULL THEN "LOCAL_ORDER_ID" END
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 AND SQLCODE != -942 AND SQLCODE != -904 THEN
            RAISE;
        END IF;
END;
/
