CREATE TABLE TB_ORDER_SYNC_LOGS (
    ID RAW(16) PRIMARY KEY,
    STORE_ID RAW(16) NOT NULL,
    ORDER_ID RAW(16),
    LOCAL_ORDER_ID VARCHAR2(100),
    DEVICE_ID VARCHAR2(150),
    STATUS VARCHAR2(30) NOT NULL,
    MESSAGE VARCHAR2(255),
    SYNCED_AT TIMESTAMP NOT NULL,

    CONSTRAINT FK_ORDER_SYNC_LOG_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES TB_ORDERS(ID)
);