ALTER TABLE TB_PRODUCT_CATEGORIES
ADD STORE_ID RAW(16);

ALTER TABLE TB_PRODUCT_CATEGORIES
ADD UPDATED_AT TIMESTAMP;

UPDATE TB_PRODUCT_CATEGORIES
SET UPDATED_AT = CREATED_AT
WHERE UPDATED_AT IS NULL;

UPDATE TB_PRODUCT_CATEGORIES c
SET c.STORE_ID = (
    SELECT MIN(p.STORE_ID)
    FROM TB_PRODUCTS p
    WHERE p.CATEGORY_ID = c.ID
)
WHERE c.STORE_ID IS NULL
  AND EXISTS (
    SELECT 1
    FROM TB_PRODUCTS p
    WHERE p.CATEGORY_ID = c.ID
  );

CREATE INDEX IDX_PRODUCT_CATEGORIES_STORE
ON TB_PRODUCT_CATEGORIES (STORE_ID);

CREATE UNIQUE INDEX UK_PRODUCT_CATEGORIES_STORE_NAME_ACTIVE
ON TB_PRODUCT_CATEGORIES (
    STORE_ID,
    LOWER(NAME),
    ACTIVE
);