DROP INDEX UK_ORDERS_DEVICE_LOCAL;

CREATE UNIQUE INDEX UK_ORDERS_LOCAL_ORDER_ID
ON TB_ORDERS (
    CASE WHEN LOCAL_ORDER_ID IS NOT NULL THEN LOCAL_ORDER_ID END
);

CREATE INDEX IDX_ORDERS_STORE_CREATED
ON TB_ORDERS (STORE_ID, CREATED_AT);