BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX "uk_orders_device_local"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 AND SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX "UK_ORDERS_DEVICE_LOCAL"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 AND SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE UNIQUE INDEX "uk_orders_local_order_id"
        ON "tb_orders" (
            CASE WHEN "local_order_id" IS NOT NULL THEN "local_order_id" END
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 AND SQLCODE != -942 AND SQLCODE != -904 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE UNIQUE INDEX "UK_ORDERS_LOCAL_ORDER_ID"
        ON "TB_ORDERS" (
            CASE WHEN "LOCAL_ORDER_ID" IS NOT NULL THEN "LOCAL_ORDER_ID" END
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 AND SQLCODE != -942 AND SQLCODE != -904 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "idx_orders_store_created" ON "tb_orders" ("store_id", "created_at")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 AND SQLCODE != -942 AND SQLCODE != -904 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "IDX_ORDERS_STORE_CREATED" ON "TB_ORDERS" ("STORE_ID", "CREATED_AT")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 AND SQLCODE != -942 AND SQLCODE != -904 THEN
            RAISE;
        END IF;
END;
/
