#!/bin/bash
set -euo pipefail

sqlplus -s / as sysdba <<SQL
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER SIGNAL_AUTH IDENTIFIED BY "${ORACLE_APP_PASSWORD}" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO SIGNAL_AUTH;

CREATE USER SIGNAL_SALES IDENTIFIED BY "${ORACLE_APP_PASSWORD}" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO SIGNAL_SALES;

CREATE USER SIGNAL_PAYMENT IDENTIFIED BY "${ORACLE_APP_PASSWORD}" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO SIGNAL_PAYMENT;

CREATE USER SIGNAL_ANALYTICS IDENTIFIED BY "${ORACLE_APP_PASSWORD}" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO SIGNAL_ANALYTICS;
SQL
