-- DDL consolidado da solucao OffPay para Azure SQL
-- As migrations Oracle originais permanecem no projeto.
-- Este arquivo atende ao requisito academico de entrega com o schema
-- consolidado usado no ambiente alvo em nuvem.

CREATE TABLE TB_USERS (
    ID uniqueidentifier PRIMARY KEY,
    NAME varchar(120) NOT NULL,
    EMAIL varchar(120) NOT NULL UNIQUE,
    PASSWORD varchar(255) NOT NULL,
    ROLE varchar(20) NOT NULL,
    CPF varchar(14) NOT NULL,
    PHONE varchar(20) NOT NULL,
    CREATED_AT datetime2 NOT NULL,
    CONSTRAINT UK_USERS_CPF UNIQUE (CPF)
);

CREATE TABLE TB_STORES (
    ID uniqueidentifier PRIMARY KEY,
    NAME varchar(120) NOT NULL,
    CATEGORY varchar(80) NOT NULL,
    USER_ID uniqueidentifier NOT NULL,
    CREATED_AT datetime2 NOT NULL,
    CONSTRAINT FK_STORE_USER FOREIGN KEY (USER_ID) REFERENCES TB_USERS(ID)
);

CREATE TABLE TB_CUSTOMER_OFFLINE_SESSIONS (
    ID uniqueidentifier PRIMARY KEY,
    USER_ID uniqueidentifier NOT NULL,
    SESSION_TOKEN varchar(255) NOT NULL,
    EXPIRES_AT datetime2 NOT NULL,
    ACTIVE bit NOT NULL,
    CREATED_AT datetime2 NOT NULL,
    CONSTRAINT FK_CUSTOMER_OFFLINE_USER FOREIGN KEY (USER_ID) REFERENCES TB_USERS(ID),
    CONSTRAINT UK_CUSTOMER_OFFLINE_USER UNIQUE (USER_ID),
    CONSTRAINT UK_CUSTOMER_OFFLINE_TOKEN UNIQUE (SESSION_TOKEN)
);

CREATE TABLE TB_PRODUCT_CATEGORIES (
    ID uniqueidentifier PRIMARY KEY,
    STORE_ID uniqueidentifier NULL,
    NAME varchar(100) NOT NULL,
    DESCRIPTION varchar(255) NULL,
    ACTIVE bit NOT NULL,
    CREATED_AT datetime2 NOT NULL,
    UPDATED_AT datetime2 NULL
);

CREATE INDEX IDX_PRODUCT_CATEGORIES_STORE
ON TB_PRODUCT_CATEGORIES (STORE_ID);

CREATE UNIQUE INDEX UK_PRODUCT_CATEGORIES_STORE_NAME_ACTIVE
ON TB_PRODUCT_CATEGORIES (STORE_ID, NAME, ACTIVE);

CREATE TABLE TB_PRODUCTS (
    ID uniqueidentifier PRIMARY KEY,
    STORE_ID uniqueidentifier NOT NULL,
    CATEGORY_ID uniqueidentifier NOT NULL,
    NAME varchar(120) NOT NULL,
    DESCRIPTION varchar(255) NULL,
    PRICE decimal(10, 2) NOT NULL,
    STOCK_QUANTITY int NOT NULL,
    ACTIVE bit NOT NULL,
    CREATED_AT datetime2 NOT NULL,
    UPDATED_AT datetime2 NULL,
    CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES TB_PRODUCT_CATEGORIES(ID)
);

CREATE INDEX IDX_PRODUCTS_STORE_CATEGORY_ACTIVE
ON TB_PRODUCTS (STORE_ID, CATEGORY_ID, ACTIVE);

CREATE TABLE TB_CATALOG_SYNC_LOGS (
    ID uniqueidentifier PRIMARY KEY,
    STORE_ID uniqueidentifier NOT NULL,
    PRODUCT_ID uniqueidentifier NULL,
    OPERATION varchar(50) NOT NULL,
    QUANTITY_DELTA int NULL,
    PRODUCT_NAME varchar(120) NULL,
    CATEGORY_ID uniqueidentifier NULL,
    PRICE decimal(10, 2) NULL,
    STOCK_QUANTITY int NULL,
    LOCAL_UPDATED_AT datetime2 NOT NULL,
    SYNCED_AT datetime2 NOT NULL,
    STATUS varchar(30) NOT NULL,
    MESSAGE varchar(255) NULL,
    OPERATION_ID varchar(100) NULL,
    CONSTRAINT FK_CATALOG_SYNC_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES TB_PRODUCTS(ID)
);

CREATE UNIQUE INDEX UK_CATALOG_SYNC_OPERATION_ID
ON TB_CATALOG_SYNC_LOGS (OPERATION_ID)
WHERE OPERATION_ID IS NOT NULL;

CREATE TABLE TB_ORDERS (
    ID uniqueidentifier PRIMARY KEY,
    LOCAL_ORDER_ID varchar(100) NULL,
    STORE_ID uniqueidentifier NOT NULL,
    CUSTOMER_ID uniqueidentifier NULL,
    SELLER_ID uniqueidentifier NULL,
    ORDER_STATUS varchar(40) NOT NULL,
    PAYMENT_STATUS varchar(40) NOT NULL,
    SYNC_STATUS varchar(40) NOT NULL,
    TOTAL_AMOUNT decimal(10, 2) NOT NULL,
    CREATED_AT datetime2 NOT NULL,
    UPDATED_AT datetime2 NULL,
    OFFLINE_CREATED_AT datetime2 NULL
);

CREATE TABLE TB_ORDER_ITEMS (
    ID uniqueidentifier PRIMARY KEY,
    ORDER_ID uniqueidentifier NOT NULL,
    PRODUCT_ID uniqueidentifier NOT NULL,
    PRODUCT_NAME varchar(120) NOT NULL,
    UNIT_PRICE decimal(10, 2) NOT NULL,
    QUANTITY int NOT NULL,
    TOTAL_PRICE decimal(10, 2) NOT NULL,
    CONSTRAINT FK_ORDER_ITEMS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES TB_ORDERS(ID),
    CONSTRAINT FK_ORDER_ITEMS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES TB_PRODUCTS(ID)
);

CREATE TABLE TB_ORDER_SYNC_LOGS (
    ID uniqueidentifier PRIMARY KEY,
    STORE_ID uniqueidentifier NOT NULL,
    ORDER_ID uniqueidentifier NULL,
    LOCAL_ORDER_ID varchar(100) NULL,
    STATUS varchar(30) NOT NULL,
    MESSAGE varchar(255) NULL,
    SYNCED_AT datetime2 NOT NULL,
    CONSTRAINT FK_ORDER_SYNC_LOG_ORDER FOREIGN KEY (ORDER_ID) REFERENCES TB_ORDERS(ID)
);

CREATE TABLE TB_PAYMENT_EVENT_OUTBOX (
    ID uniqueidentifier PRIMARY KEY,
    ORDER_ID uniqueidentifier NOT NULL,
    EVENT_TYPE varchar(60) NOT NULL,
    PAYLOAD_JSON varchar(max) NOT NULL,
    STATUS varchar(20) NOT NULL,
    ATTEMPTS int NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT datetime2 NOT NULL,
    LAST_ERROR varchar(255) NULL,
    CREATED_AT datetime2 NOT NULL,
    UPDATED_AT datetime2 NOT NULL,
    SENT_AT datetime2 NULL,
    CONSTRAINT FK_PAYMENT_EVENT_OUTBOX_ORDER FOREIGN KEY (ORDER_ID) REFERENCES TB_ORDERS(ID)
);

CREATE UNIQUE INDEX UK_PAYMENT_EVENT_OUTBOX_ORDER
ON TB_PAYMENT_EVENT_OUTBOX (ORDER_ID);

CREATE INDEX IDX_PAYMENT_EVENT_OUTBOX_STATUS_NEXT
ON TB_PAYMENT_EVENT_OUTBOX (STATUS, NEXT_ATTEMPT_AT);

CREATE TABLE TB_WALLETS (
    ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    OWNER_ID uniqueidentifier NOT NULL,
    OWNER_TYPE varchar(20) NOT NULL,
    BALANCE decimal(15, 2) NOT NULL DEFAULT 0,
    PENDING_BALANCE decimal(15, 2) NOT NULL DEFAULT 0,
    CREATED_AT datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UK_WALLETS_OWNER UNIQUE (OWNER_ID, OWNER_TYPE)
);

CREATE TABLE TB_WALLET_TRANSACTIONS (
    ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    WALLET_ID uniqueidentifier NOT NULL,
    TYPE varchar(40) NOT NULL,
    AMOUNT decimal(15, 2) NOT NULL,
    DESCRIPTION varchar(255) NULL,
    REFERENCE_ID varchar(100) NULL,
    CREATED_AT datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_WALLET_TRANSACTIONS_WALLET FOREIGN KEY (WALLET_ID) REFERENCES TB_WALLETS(ID)
);

CREATE TABLE TB_PAYMENT_TRANSACTIONS (
    ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    ORDER_ID uniqueidentifier NOT NULL,
    LOCAL_ORDER_ID varchar(100) NULL,
    CUSTOMER_ID uniqueidentifier NULL,
    SELLER_ID uniqueidentifier NULL,
    STORE_ID uniqueidentifier NOT NULL,
    AMOUNT decimal(15, 2) NOT NULL,
    STATUS varchar(30) NOT NULL,
    FAILURE_REASON varchar(255) NULL,
    GATEWAY_REFERENCE varchar(100) NULL,
    CREDIT_DEBT_AMOUNT decimal(15, 2) NOT NULL DEFAULT 0,
    CREATED_AT datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),
    PROCESSED_AT datetime2 NULL,
    CREDIT_DEBT_SETTLED_AT datetime2 NULL,
    CONSTRAINT UK_PAYMENT_TRANSACTIONS_ORDER UNIQUE (ORDER_ID)
);

CREATE TABLE TB_PAYMENT_PROCESSED_OUTBOX (
    ID uniqueidentifier PRIMARY KEY,
    ORDER_ID uniqueidentifier NOT NULL,
    EVENT_TYPE varchar(60) NOT NULL,
    PAYLOAD_JSON varchar(max) NOT NULL,
    STATUS varchar(20) NOT NULL,
    ATTEMPTS int NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT datetime2 NOT NULL,
    LAST_ERROR varchar(255) NULL,
    CREATED_AT datetime2 NOT NULL,
    UPDATED_AT datetime2 NOT NULL,
    SENT_AT datetime2 NULL,
    CONSTRAINT FK_PAYMENT_PROCESSED_OUTBOX_ORDER FOREIGN KEY (ORDER_ID) REFERENCES TB_PAYMENT_TRANSACTIONS(ORDER_ID)
);

CREATE UNIQUE INDEX UK_PAYMENT_PROCESSED_OUTBOX_ORDER
ON TB_PAYMENT_PROCESSED_OUTBOX (ORDER_ID);

CREATE INDEX IDX_PAYMENT_PROCESSED_OUTBOX_STATUS_NEXT
ON TB_PAYMENT_PROCESSED_OUTBOX (STATUS, NEXT_ATTEMPT_AT);

CREATE TABLE KNOWLEDGE_CHUNK (
    ID bigint IDENTITY(1,1) PRIMARY KEY,
    SOURCE_NAME varchar(120) NOT NULL,
    TITLE varchar(200) NOT NULL,
    CHUNK_INDEX int NOT NULL,
    CONTENT varchar(max) NOT NULL,
    NORMALIZED_CONTENT varchar(max) NOT NULL
);

CREATE INDEX IDX_KNOWLEDGE_CHUNK_SOURCE
ON KNOWLEDGE_CHUNK (SOURCE_NAME);

CREATE INDEX IDX_KNOWLEDGE_CHUNK_SOURCE_CHUNK
ON KNOWLEDGE_CHUNK (SOURCE_NAME, CHUNK_INDEX);
