CREATE TABLE TB_WALLETS (
    ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    OWNER_ID uniqueidentifier NOT NULL,
    OWNER_TYPE varchar(20) NOT NULL,
    BALANCE decimal(15, 2) NOT NULL DEFAULT 0,
    PENDING_BALANCE decimal(15, 2) NOT NULL DEFAULT 0,
    CREATED_AT datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UPDATED_AT datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UK_WALLETS_OWNER UNIQUE (OWNER_ID, OWNER_TYPE)
);

CREATE TABLE TB_WALLET_TRANSACTIONS (
    ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    WALLET_ID uniqueidentifier NOT NULL,
    TYPE varchar(40) NOT NULL,
    AMOUNT decimal(15, 2) NOT NULL,
    DESCRIPTION varchar(255) NULL,
    REFERENCE_ID varchar(100) NULL,
    CREATED_AT datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_WALLET_TRANSACTIONS_WALLET
        FOREIGN KEY (WALLET_ID)
        REFERENCES TB_WALLETS(ID)
);

CREATE TABLE TB_PAYMENT_TRANSACTIONS (
    ID uniqueidentifier PRIMARY KEY DEFAULT NEWID(),
    ORDER_ID uniqueidentifier NOT NULL,
    LOCAL_ORDER_ID varchar(100) NULL,
    CUSTOMER_ID uniqueidentifier NULL,
    SELLER_ID uniqueidentifier NULL,
    STORE_ID uniqueidentifier NOT NULL,
    AMOUNT decimal(15, 2) NOT NULL,
    STATUS varchar(30) NOT NULL,
    FAILURE_REASON varchar(255) NULL,
    GATEWAY_REFERENCE varchar(100) NULL,
    CREDIT_DEBT_AMOUNT decimal(15, 2) NOT NULL DEFAULT 0,
    CREATED_AT datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),
    PROCESSED_AT datetime2 NULL,
    CREDIT_DEBT_SETTLED_AT datetime2 NULL,
    CONSTRAINT UK_PAYMENT_TRANSACTIONS_ORDER UNIQUE (ORDER_ID)
);

CREATE TABLE TB_PAYMENT_PROCESSED_OUTBOX (
    ID uniqueidentifier PRIMARY KEY,
    ORDER_ID uniqueidentifier NOT NULL,
    EVENT_TYPE varchar(60) NOT NULL,
    PAYLOAD_JSON varchar(max) NOT NULL,
    STATUS varchar(20) NOT NULL,
    ATTEMPTS int NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT datetime2 NOT NULL,
    LAST_ERROR varchar(255) NULL,
    CREATED_AT datetime2 NOT NULL,
    UPDATED_AT datetime2 NOT NULL,
    SENT_AT datetime2 NULL,
    CONSTRAINT FK_PAYMENT_PROCESSED_OUTBOX_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES TB_PAYMENT_TRANSACTIONS(ORDER_ID)
);

CREATE UNIQUE INDEX UK_PAYMENT_PROCESSED_OUTBOX_ORDER
ON TB_PAYMENT_PROCESSED_OUTBOX (ORDER_ID);

CREATE INDEX IDX_PAYMENT_PROCESSED_OUTBOX_STATUS_NEXT
ON TB_PAYMENT_PROCESSED_OUTBOX (STATUS, NEXT_ATTEMPT_AT);
