CREATE TABLE TB_USERS (
    ID RAW(16) PRIMARY KEY,
    NAME VARCHAR2(120) NOT NULL,
    EMAIL VARCHAR2(120) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE TB_STORES (
    ID RAW(16) PRIMARY KEY,
    NAME VARCHAR2(120) NOT NULL,
    CATEGORY VARCHAR2(80) NOT NULL,
    USER_ID RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_STORE_USER FOREIGN KEY (USER_ID) REFERENCES TB_USERS(ID)
);

CREATE TABLE TB_DEVICES (
    ID RAW(16) PRIMARY KEY,
    DEVICE_ID VARCHAR2(255) NOT NULL UNIQUE,
    OFFLINE_TOKEN VARCHAR2(255) NOT NULL,
    OFFLINE_EXPIRES_AT TIMESTAMP NOT NULL,
    ACTIVE NUMBER(1) NOT NULL,
    USER_ID RAW(16) NOT NULL,
    CONSTRAINT FK_DEVICE_USER FOREIGN KEY (USER_ID) REFERENCES TB_USERS(ID)
);