ALTER TABLE TB_USERS
ADD CPF VARCHAR2(14);

ALTER TABLE TB_USERS
ADD PHONE VARCHAR2(20);

UPDATE TB_USERS
SET CPF = 'TEMP' || LPAD(ROWNUM, 10, '0'),
    PHONE = '00000000000'
WHERE CPF IS NULL;

ALTER TABLE TB_USERS
MODIFY CPF VARCHAR2(14) NOT NULL;

ALTER TABLE TB_USERS
MODIFY PHONE VARCHAR2(20) NOT NULL;

ALTER TABLE TB_USERS
ADD CONSTRAINT UK_USERS_CPF UNIQUE (CPF);