CREATE TABLE TB_CUSTOMER_OFFLINE_SESSIONS (
    ID RAW(16) PRIMARY KEY,
    USER_ID RAW(16) NOT NULL,
    SESSION_TOKEN VARCHAR2(255) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    ACTIVE NUMBER(1) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,

    CONSTRAINT FK_CUSTOMER_OFFLINE_USER
        FOREIGN KEY (USER_ID)
        REFERENCES TB_USERS(ID),

    CONSTRAINT UK_CUSTOMER_OFFLINE_USER
        UNIQUE (USER_ID),

    CONSTRAINT UK_CUSTOMER_OFFLINE_TOKEN
        UNIQUE (SESSION_TOKEN)
);